### ISSUE TITLE
New release for the Linux ARM64 support

### ISSUE THREAD

**Issue by martin-g** [Maihj/AC-DIAMOND#11]
Hello,

Could you please make a new release (a Git tag) that includes the improvements in https://github.com/Maihj/AC-DIAMOND/pull/8/files ?
We need it for the Bioconda recipe (https://github.com/bioconda/bioconda-recipes/blob/d0879b8111b6ccdb343fb027bddca6a064febe67/recipes/ac-diamond/meta.yaml#L6) 

Thank you!

**Comment by aquaskyline** [comment]
release `pr8` is created.

**Comment by martin-g** [comment]
Thank you, @aquaskyline !
