### ISSUE TITLE
Error: option '--sensitive' is ambiguous

### ISSUE THREAD

**Issue by slhogle** [Maihj/AC-DIAMOND#2]
Hi there,

I'm trying to build an ac-diamond database for sensitive search but am getting an error:

Command: `ac-diamond makedb --sensitive --in RL03.faa -d RL03.sensitive.index -b 4`
Error: `Error: option '--sensitive' is ambiguous and matches different versions of '--sensitive'`

ac-diamond v1.0 built from source
Running RedHat Linux CentOS release 6.8

best,
-shane

**Comment by Maihj** [comment]
Hello Shane,
The problem has been fixed. Please try to rebuild the software.

best,
Huijun

**Comment by slhogle** [comment]
Hi Huijun,

great thanks - all is working now

cheers,
-shane

**Comment by s-j-mc** [comment]
Hi Huijun,

I am using AC-Diamond through conda, and I am receiving the same issue:

Command: `ac-diamond makedb --in nrdb.fasta -d nr --threads 100 --sensitive`
Error: `Error: option '--sensitive' is ambiguous and matches different versions of '--sensitive'`

AC-Diamond Conda version:
ac-diamond                1.0                  h02d93b8_1    bioconda

Would it be possible to make the fix also available when using conda?

Thanks
Sam
